# fly.toml app configuration file generated for mysqlkath on 2024-02-08T15:19:37+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mysqlkath'
primary_region = 'arn'

[build]
  image = 'mysql:8'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

# Add the following sections
[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"